server:
  port: 8081
  

spring:
  application:
    name: user-service
  
# spring:
#   security:
#     user:
#       name: user
#       password: password
    
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

jwt:
  secret: qFzpAWxUQj6AxyA9PQZtKUEFDY0vBDfF+QzduzC5aMXbKDTh7rKhxC97qzn8FRXwcewU3QXYgy+EelJcFvDi+A==           
  expiration: 3600000


# Database configuration (example)
# Uncomment and configure according to your database setup
# datasource:
#   url: jdbc:mysql://localhost:3306/userdb
#   username: your_username
#   password: your_password
#   driver-class-name: com.mysql.cj.jdbc.Driver

# Other service-specific configurations can be added here.