server:
  port: 8081

spring:
  application:
    name: user-service

logging:
  level:
    root: INFO
    com.cib.user: DEBUG

# Database configuration (example)
# Uncomment and configure according to your database setup
# datasource:
#   url: jdbc:mysql://localhost:3306/userdb
#   username: your_username
#   password: your_password
#   driver-class-name: com.mysql.cj.jdbc.Driver

# Other service-specific configurations can be added here.