server:
  port: 8084

spring:
  application:
    name: notification-service

logging:
  level:
    root: INFO
    com.cib.notification: DEBUG

# Add any other configuration properties specific to the notification service here.