server:
  port: 8088

spring:
  application:
    name: compliance-service

logging:
  level:
    root: INFO
    com.cib.compliance: DEBUG

# Database configuration (example)
# Uncomment and configure as needed
# datasource:
#   url: jdbc:mysql://localhost:3306/compliance_db
#   username: your_username
#   password: your_password
#   driver-class-name: com.mysql.cj.jdbc.Driver

# Other service-specific configurations can be added here.