server:
  port: 8083

spring:
  application:
    name: transaction-service

logging:
  level:
    root: INFO
    com.cib.transaction: DEBUG

# Database configuration (example)
# Uncomment and configure as needed
# datasource:
#   url: jdbc:mysql://localhost:3306/transaction_db
#   username: your_username
#   password: your_password
#   driver-class-name: com.mysql.cj.jdbc.Driver

# Other service-specific configurations can be added here.