server:
  port: 8085

spring:
  application:
    name: audit-service

logging:
  level:
    root: INFO
    com.cib.audit: DEBUG

# Database configuration (example)
# Uncomment and configure if using a database
# datasource:
#   url: jdbc:mysql://localhost:3306/audit_db
#   username: your_username
#   password: your_password
#   driver-class-name: com.mysql.cj.jdbc.Driver

# Other service-specific configurations can be added here.