--
-- Portfolio Table
--

CREATE TABLE IF NOT EXISTS portfolio (
    id BIGSERIAL PRIMARY KEY,
    portfolionumber VARCHAR(100) NOT NULL UNIQUE,
    portfoliotype VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    user_id BIGINT NOT NULL,
    startdate DATE,
    updateddate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    enddate DATE, 
    end_date DATE,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    start_date DATE,
    portfolio_number VARCHAR(100),
    portfolio_type VARCHAR(50),

    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);


INSERT INTO portfolio VALUES (1, 'PORT1001', 'SAVINGS', 'ACTIVE', 1, '2025-06-01', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO portfolio VALUES (2, 'PORT1002', 'CURRENT', 'ACTIVE', 1, '2025-06-02', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO portfolio VALUES (3, 'PORT1003', 'SAVINGS', 'ACTIVE', 2, '2025-06-03', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO portfolio VALUES (4, 'PORT1004', 'CURRENT', 'INACTIVE', 2, '2025-06-04', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO portfolio VALUES (5, 'PORT1005', 'SAVINGS', 'ACTIVE', 3, '2025-06-05', NULL, NULL, NULL, NULL, NULL, NULL, NULL);
