--
-- User Table
--
CREATE TABLE IF NOT EXISTS "user" (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email_id VARCHAR(255) NOT NULL,
    end_date DATE,
    first_name VARCHAR(100) NOT NULL,
    identity_number VARCHAR(50) UNIQUE,
    last_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20),
    role VARCHAR(50),
    start_date DATE NOT NULL,
    updated_date TIMESTAMP(6) WITHOUT TIME ZONE,
    address_id BIGINT,
    portfolio_id BIGINT,

    CONSTRAINT fk_address FOREIGN KEY (address_id)
        REFERENCES addresses(id)
        ON UPDATE NO ACTION ON DELETE NO ACTION,

    CONSTRAINT fk_portfolio FOREIGN KEY (portfolio_id)
        REFERENCES portfolio(id)
        ON UPDATE NO ACTION ON DELETE NO ACTION
);


INSERT INTO "user" VALUES (1, 'harshitha.s1@example.com', NULL, 'Harshitha', 'ID10001', 'S', '1234567890', 'USER', '2025-07-01', '2025-07-18 05:42:47.294957', 1, 1);
INSERT INTO "user" VALUES (2, 'priya.l9@example.com', NULL, 'Priya', 'ID10009', 'L', '1234567898', 'USER', '2025-07-09', '2025-07-18 05:42:47.294957', 1, 1);
INSERT INTO "user" VALUES (3, 'rohit.k2@example.com', NULL, 'Rohit', 'ID10002', 'K', '1234567891', 'ADMIN', '2025-07-02', '2025-07-18 05:42:47.294957', 2, 3);
INSERT INTO "user" VALUES (4, 'anjali.m3@example.com', NULL, 'Anjali', 'ID10003', 'M', '1234567892', 'USER', '2025-07-03', '2025-07-18 05:42:47.294957', 3, 5);
INSERT INTO "user" VALUES (5, 'vikram.t4@example.com', NULL, 'Vikram', 'ID10004', 'T', '1234567893', 'USER', '2025-07-04', '2025-07-18 05:42:47.294957', 4, 2);