server:
  port: 8085

spring:
  application:
    name: fund-manager-service

logging:
  level:
    root: INFO
    com.cib.fundmanager: DEBUG

# Database configuration (example)
# Uncomment and configure as needed
# datasource:
#   url: jdbc:mysql://localhost:3306/fund_manager
#   username: your_username
#   password: your_password
#   driver-class-name: com.mysql.cj.jdbc.Driver

# JPA/Hibernate configuration (example)
# Uncomment and configure as needed
# jpa:
#   hibernate:
#     ddl-auto: update
#   show-sql: true

# Other service-specific configurations can be added here.