server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nithish
    username: postgres
    password: 172003
  jpa:
    hibernate:
      ddl-auto: validate  # let Flyway manage schema
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
logging:
  level:
    root: INFO
    com.cib.portfolio: DEBUG

  