server:
  port: 8083

spring:
  application:
    name: transaction-service

  datasource:
    url:  jdbc:postgresql://localhost:3005/transaction_db
    username: root20
    password: root20

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


logging:
  level:
    root: INFO
    com.cib.transaction: DEBUG




