version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: compliance-postgres
    environment:
      POSTGRES_DB: complianceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    networks:
      - compliance-network

  compliance-service:
    image: compliance-service-appln
    container_name: compliance-service
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/complianceDb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SERVER_PORT: 8080
      SERVER_ADDRESS: 0.0.0.0
    networks:
      - compliance-network

networks:
  compliance-network: